import java.awt.EventQueue;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextArea;

import org.jdesktop.swingx.JXDatePicker;

import javax.swing.JScrollPane;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.JLabel;

import java.awt.Color;
import java.util.Vector;

import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class CalendarUI {

	private JFrame frame;
	private JTextField textField;
	private JTable tableEvents;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					CalendarUI window = new CalendarUI();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public CalendarUI() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 803, 450);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);
		
		JTextArea txtAreaEventDescription = new JTextArea();
		txtAreaEventDescription.setToolTipText("Enter event information here for a selected date from the calendar.");
		txtAreaEventDescription.setText("Enter event info for your chosen date.");
		txtAreaEventDescription.setBounds(324, 10, 304, 190);
		frame.getContentPane().add(txtAreaEventDescription);
		
		textField = new JTextField();
		textField.setBounds(638, 45, 86, 20);
		frame.getContentPane().add(textField);
		textField.setColumns(10);
		
		CalendarPopulator calendarPopulator = new CalendarPopulator();
		calendarPopulator.setBounds(10, 10, 304, 190);
		frame.getContentPane().add(calendarPopulator);
		
		JScrollPane scrollPaneEvents = new JScrollPane();
		scrollPaneEvents.setBounds(10, 207, 618, 190);
		frame.getContentPane().add(scrollPaneEvents);
		
		tableEvents = new JTable();
		tableEvents.setShowGrid(false);
		
		DefaultTableModel dtModel = new DefaultTableModel();
		
		dtModel.addColumn("Date");
		dtModel.addColumn("Time");
		dtModel.addColumn("Description");
		
		String[] test = {"YYYY-MM-DD", "HH:MM:SS", "ipsum lorem"};
		
		tableEvents.setModel(dtModel);
		tableEvents.getColumnModel().getColumn(2).setPreferredWidth(300); //set the width of the description column to the proper size
		
		dtModel.addRow(test);
		
		tableEvents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		scrollPaneEvents.setViewportView(tableEvents);
		
		JButton btnAddDescription = new JButton("Add Desc.");
		btnAddDescription.setBounds(638, 11, 89, 23);
		frame.getContentPane().add(btnAddDescription);
		
		JLabel lblInvalidTime = new JLabel("Use HH:MM:ss");
		lblInvalidTime.setForeground(Color.RED);
		lblInvalidTime.setBounds(638, 70, 86, 14);
		frame.getContentPane().add(lblInvalidTime);
		
		JButton btnAddTime = new JButton("Add Time");
		btnAddTime.setBounds(638, 95, 89, 23);
		frame.getContentPane().add(btnAddTime);
		
		JButton btnFinalized = new JButton("Add Event");
		btnFinalized.setBounds(638, 374, 89, 23);
		frame.getContentPane().add(btnFinalized);
		
		//AUTOGENERATED ABOVE BY DESIGN VIEW
		
		TablePopulator tablePop = new TablePopulator(tableEvents);
		
		ButtonListener descListener = new ButtonListener(txtAreaEventDescription);
		
		ButtonListener timeListener = new ButtonListener(textField);
		
		btnAddDescription.addActionListener(descListener);
		
		btnAddTime.addActionListener(timeListener);
		
		btnFinalized.addActionListener(new EventAssemblyListener(calendarPopulator, descListener, timeListener));
		
		//TODO below hook in all the listeners
		
	}
}
