import java.awt.EventQueue;

import javax.swing.JFrame;
import com.jgoodies.forms.layout.FormLayout;
import com.jgoodies.forms.layout.ColumnSpec;
import com.jgoodies.forms.layout.RowSpec;
import com.jgoodies.forms.factories.FormFactory;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;


public class Calculator {

	private JFrame frame;
	private JTextField txtTargetAC;
	private JTextField txtCombatSkill;
	private JTextField txtAttrMod;
	private JTextField txtAttkBonus;
	private JTextField txtTotal;
	private JTextField txtAttkDice;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Calculator window = new Calculator();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public Calculator() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 450, 300);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);
		
		JLabel lblTargetAC = new JLabel("Target AC");
		lblTargetAC.setBounds(6, 6, 75, 14);
		frame.getContentPane().add(lblTargetAC);
		
		txtTargetAC = new JTextField();
		txtTargetAC.setBounds(82, 3, 86, 20);
		frame.getContentPane().add(txtTargetAC);
		txtTargetAC.setColumns(10);
		
		JLabel lblCombatSkill = new JLabel("Combat Skill");
		lblCombatSkill.setBounds(6, 36, 75, 14);
		frame.getContentPane().add(lblCombatSkill);
		
		txtCombatSkill = new JTextField();
		txtCombatSkill.setBounds(82, 33, 86, 20);
		frame.getContentPane().add(txtCombatSkill);
		txtCombatSkill.setColumns(10);
		
		JLabel lblAttrMod = new JLabel("Attr. Mod.");
		lblAttrMod.setBounds(6, 66, 75, 14);
		frame.getContentPane().add(lblAttrMod);
		
		txtAttrMod = new JTextField();
		txtAttrMod.setBounds(82, 63, 86, 20);
		frame.getContentPane().add(txtAttrMod);
		txtAttrMod.setColumns(10);
		
		JLabel lblAttkBonus = new JLabel("Attk Bonus");
		lblAttkBonus.setBounds(6, 96, 75, 14);
		frame.getContentPane().add(lblAttkBonus);
		
		txtAttkBonus = new JTextField();
		txtAttkBonus.setBounds(82, 93, 86, 20);
		frame.getContentPane().add(txtAttkBonus);
		txtAttkBonus.setColumns(10);
		
		JButton btnSumTotal = new JButton("Average");
		btnSumTotal.setBounds(0, 153, 75, 20);
		frame.getContentPane().add(btnSumTotal);
		
		txtTotal = new JTextField();
		txtTotal.setEditable(false);
		txtTotal.setBounds(82, 153, 86, 20);
		frame.getContentPane().add(txtTotal);
		txtTotal.setColumns(10);
		
		JLabel lblAttkDice = new JLabel("Attk Dice");
		lblAttkDice.setBounds(6, 126, 75, 14);
		frame.getContentPane().add(lblAttkDice);
		
		txtAttkDice = new JTextField();
		txtAttkDice.setBounds(82, 123, 86, 20);
		frame.getContentPane().add(txtAttkDice);
		txtAttkDice.setColumns(10);
		
		//=========================Autogenerated Done ============================
		
		btnSumTotal.addActionListener(new RollAverageListener(txtTotal, txtAttkDice, txtTargetAC, txtCombatSkill, txtAttrMod, txtAttkBonus));
		
	}
}
